CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(20),
    tipo_usuario VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS especialidades (
    id_especialidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255),
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS pacientes (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,

    FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS profissionais (
    id_profissional INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    registro_profissional VARCHAR(50) NOT NULL UNIQUE,
    descricao VARCHAR(255),
    id_especialidade INTEGER NOT NULL,

    FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id_usuario),

    FOREIGN KEY (id_especialidade)
    REFERENCES especialidades(id_especialidade)
);

CREATE TABLE IF NOT EXISTS disponibilidades (
    id_disponibilidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profissional INTEGER NOT NULL,
    data DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,

    FOREIGN KEY (id_profissional)
    REFERENCES profissionais(id_profissional)
);

CREATE TABLE IF NOT EXISTS consultas (
    id_consulta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_profissional INTEGER NOT NULL,
    id_disponibilidade INTEGER NOT NULL UNIQUE,
    data_agendamento TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,
    observacao VARCHAR(500),

    FOREIGN KEY (id_paciente)
    REFERENCES pacientes(id_paciente),

    FOREIGN KEY (id_profissional)
    REFERENCES profissionais(id_profissional),

    FOREIGN KEY (id_disponibilidade)
    REFERENCES disponibilidades(id_disponibilidade)
);

CREATE TABLE IF NOT EXISTS acompanhamentos (
    id_acompanhamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta INTEGER NOT NULL,
    data_acompanhamento DATE NOT NULL,
    observacao VARCHAR(500),
    status VARCHAR(30),
    FOREIGN KEY (id_consulta)
    REFERENCES consultas(id_consulta)
);